# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5e229983a2121b52aeceb31300d9921d85fa0c739820fcf4d2987d5b88294e3c86012481305142dfac021dde3285899d87cf51c36a70618e96b57db60178e66

test:
  secret_key_base: d3031c69cbeb0933e9059c329eb1f3f8fed90476d736664caf8ba1e8666107cd6bb7392239cf69c0f1b9041a739ec0ecf65d7d874cf6088705e127cb43152c8c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
